{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "playwright-manager.fullname" . }}
  labels:
    {{- include "playwright-manager.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "playwright-manager.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- with .Values.hpa.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
