{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playwright-manager.secretName" . }}
  labels:
    {{- include "playwright-manager.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "playwright-manager.databaseUrl" . | quote }}
{{- end }}
